// routes.ts
interface AppRoute {
  path: string;
  enabled: boolean;
}

export const appRoutes: AppRoute[] = [
  { path: "/", enabled: false },
  { path: "/boost-your-practices-performance-with-revenue-cycle-kpis", enabled: false },
  { path: "/top-20-healthcare-technology-trends", enabled: false },
  { path: "/what-is-medical-billing-and-coding", enabled: false },
  { path: "/how-AI-is-improving-medical-coding-processes-accuracy-and-efficiency", enabled: false }, // disabled during maintenance
  { path: "/how-chiropractic-billing-services-work-for-medicare-beneficiaries", enabled: false },
  { path: "/how-medical-coding-impacts-the-revenue-cycle", enabled: false },
  { path: "/optimize-healthcare-Finances-rcm-mastery-unleashed", enabled: false },
  { path: "/free-ationevalu", enabled: false },
  { path: "/rcm-assessment", enabled: false },
  { path: "/pricing", enabled: false },
  { path: "/rcm-plans", enabled: false },
  { path: "/cardiology-billing-services", enabled: false },
  { path: "/denial-management-service", enabled: false },
  { path: "/nephrology-medical-billing", enabled: false },
  { path: "/icd-10-medical-coding-services", enabled: false },
  { path: "/profit-enhancement-services", enabled: false },
  { path: "/internal-medicine-medical-billing", enabled: false },
  { path: "/medical-debt-collection-services", enabled: false },
  { path: "/medical-billing-coding", enabled: false },
  { path: "/medical-coding-services", enabled: false },
  { path: "/medical-billing-company", enabled: false },
  { path: "/medical-claim-billing-company", enabled: false },
  { path: "/our-specialities", enabled: false },
  { path: "/physician-medical-billing-company", enabled: false },
  { path: "/Physician-credentialing-services", enabled: false },
  { path: "/physician-practice-management", enabled: false },
  { path: "/radiology-billing-services", enabled: false },
  { path: "/revenue-cycle-management-services", enabled: false },
  { path: "/service-detail-old", enabled: false },
  { path: "/our-services", enabled: false },
  { path: "/accounts-receivable-recovery-solutions", enabled: false },
  { path: "/medical-insurance-eligibility-verification", enabled: false },
  { path: "/about-us", enabled: false },
  { path: "/blogs", enabled: false },
  { path: "/booking-old", enabled: false },
  { path: "/contact-us", enabled: false },
  { path: "/doctor-thank-you", enabled: false },
  { path: "/home", enabled: false },
  { path: "/physician-billing", enabled: false },
  { path: "/privacy-policy", enabled: false },
  { path: "/student-thank-you", enabled: false },
  { path: "/team-old", enabled: false },
  { path: "/thank-you", enabled: false },
  { path: "/new", enabled: false },
  { path: "/new/cardiology-billing-services", enabled: false },
  { path: "/new/icd-10-medical-coding-services", enabled: false },
  { path: "/new/ICD-10-medical-coding-old", enabled: false },
  { path: "/new/internal-medicine-medical-billing", enabled: false },
  { path: "/new/medical-billing-coding", enabled: false },
  { path: "/new/medical-billing-coding-services", enabled: false },
  { path: "/new/medical-billing-coding-services-old", enabled: false },
  { path: "/new/medical-claim-billing-company", enabled: false },
  { path: "/new/physician-billing-services", enabled: false },
  { path: "/new/radiology-billing-services", enabled: false },
  { path: "/new/revenue-cycle-management-company", enabled: false },
  { path: "/new/revenue-cycle-management-company/[slug]", enabled: false },
  { path: "/auth/form-forget-password", enabled: false },
  { path: "/auth/form-login", enabled: false },
  { path: "/auth/form-register", enabled: false }
];
